replicaCount: 2
image:
  repository: magazik-app-backend
  tag: "latest"
  pullPolicy: IfNotPresent
env:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres.database:5432/magazik"
  REDIS_URL: "redis://redis.cache:6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka:9092"
